# Travis CI Configuration File

sudo: false
dist: trusty

# Declare project language.
# @link https://about.travis-ci.org/docs/user/languages/php/
language: php

# test only master, stable branches and pull requests
branches:
  only:
    - master
    - /^\d.\d+$/

# Declare versions of PHP to use. Use one decimal max.
# @link https://docs.travis-ci.com/user/build-configuration/
matrix:
  fast_finish: true

  include:
    # Current $required_php_version for WordPress: 5.2.4
    # aliased to 5.2.17
    - php: '5.2'
      dist: precise
    # aliased to a recent 5.6.x version
    - php: '5.6'
      env: PHPCS=1

  allow_failures:
    # Allow failures until we fix errors
    - php: '5.6'

# Git clone depth
# By default Travis CI clones repositories to a depth of 50 commits
git:
  depth: 3

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
  # Speed up build time by disabling Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
  - |
    if [[ "$PHPCS" == "1" ]]; then
      composer install --dev --no-interaction --no-suggest
      composer config-cs
    fi

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors.
  - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

  # PHP CS
  - |
    if [[ "$PHPCS" == "1" ]]; then
      travis_fold start "PHP.code-style"
      travis_time_start
      vendor/bin/phpcs -q --runtime-set ignore_warnings_on_exit 1 || exit 1
      travis_time_finish
      travis_fold end "PHP.code-style"
      echo
    fi

# Receive notifications for build results.
# @link https://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
